services:
  gphotos-uploader:
    image: ghcr.io/giuseppe99barchetta/google-photos-uploader:latest
    container_name: gphotos-uploader
    restart: unless-stopped
    environment:
      - WATCHED_FOLDER=/data
      - AUTH_DATA=INSERT_YOUR_AUTH_DATA_HERE
    volumes:
      - ${PHOTO_FOLDER:-./photos}:/data
    # If necessary, specify the UID/GID of the user for file permissions
    # user: "1000:1000"
